# Generated by Django 5.1 on 2024-10-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0002_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
